In [1]:
 #!pip install librosa


In [2]:
"""import librosa as lib
import os
import pandas as pd
import pylab
import numpy as np
import librosa.display
import glob """

'import librosa as lib\nimport os\nimport pandas as pd\nimport pylab\nimport numpy as np\nimport librosa.display\nimport glob '

In [3]:
"""def convert(filename):   
    sig, fs = lib.load(filename)   
    # make pictures name 
    save_path = filename+'.jpg'

    pylab.axis('off') # no axis
    pylab.axes([0., 0., 1., 1.], frameon=False, xticks=[], yticks=[]) # Remove the white edge
    S = librosa.feature.melspectrogram(y=sig, sr=fs)
    lib.display.specshow(librosa.power_to_db(S, ref=np.max))
    pylab.savefig(save_path, bbox_inches=None, pad_inches=0)
    pylab.close()"""

"def convert(filename):   \n    sig, fs = lib.load(filename)   \n    # make pictures name \n    save_path = filename+'.jpg'\n\n    pylab.axis('off') # no axis\n    pylab.axes([0., 0., 1., 1.], frameon=False, xticks=[], yticks=[]) # Remove the white edge\n    S = librosa.feature.melspectrogram(y=sig, sr=fs)\n    lib.display.specshow(librosa.power_to_db(S, ref=np.max))\n    pylab.savefig(save_path, bbox_inches=None, pad_inches=0)\n    pylab.close()"

In [4]:
##"""for i in range(11):
#    for filename in glob.glob(r'D:\Projects\urban_sound\UrbanSound8K\audio\fold'+str(i)+'\*.wav'):
 #       convert(filename)"""

In [1]:
import pandas as pd
data = pd.read_csv(r'D:\Projects\urban_sound\UrbanSound8K\metadata\UrbanSound8K.csv')

In [2]:
print(data.head())

      slice_file_name    fsID  start        end  salience  fold  classID  \
0    100032-3-0-0.wav  100032    0.0   0.317551         1     5        3   
1  100263-2-0-117.wav  100263   58.5  62.500000         1     5        2   
2  100263-2-0-121.wav  100263   60.5  64.500000         1     5        2   
3  100263-2-0-126.wav  100263   63.0  67.000000         1     5        2   
4  100263-2-0-137.wav  100263   68.5  72.500000         1     5        2   

              class  
0          dog_bark  
1  children_playing  
2  children_playing  
3  children_playing  
4  children_playing  


In [3]:
test = data.loc[data['fold'] == 10]
train = data.loc[data['fold'] != 10]

In [4]:
#cv2.imshow('in',cv2.imread(r'D:\Projects\urban_sound\UrbanSound8K\audio\fold7\99812-1-6-0.wav.jpg'))


In [5]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
import os
import cv2

loc = r'D:\Projects\urban_sound\UrbanSound8K\audio'
img_lst = np.array(train.slice_file_name.tolist())
folds = np.array(train.fold)
print(img_lst.shape)
img_lst = [loc +'\\'+'fold'+str(fold)+'\\'+ s + '.jpg' for s,fold in zip(img_lst,folds)]
X = []
for s in img_lst:
    X.append(cv2.resize(cv2.imread(s, cv2.IMREAD_COLOR),(150,150),interpolation=cv2.INTER_CUBIC))
#X = [cv2.imshow('img',s) for s in X]

y = np.array(train.classID.tolist())

(7895,)


In [6]:
import gc
del train
gc.collect()

0

In [7]:
X = np.array(X)
print(X[0])
y

[[[  4   0   0]
  [  4   0   0]
  [  4   0   0]
  ...
  [  4   0   0]
  [  4   0   0]
  [  4   0   0]]

 [[ 16   5   6]
  [ 16   5   6]
  [ 16   5   6]
  ...
  [  4   0   0]
  [  4   0   0]
  [  4   0   0]]

 [[ 52  11  19]
  [ 52  11  19]
  [ 52  11  19]
  ...
  [  4   0   0]
  [  4   0   0]
  [  4   0   0]]

 ...

 [[119  19  68]
  [119  19  68]
  [119  19  68]
  ...
  [126  22  82]
  [126  22  82]
  [126  22  82]]

 [[112  14  60]
  [112  14  60]
  [112  14  60]
  ...
  [ 94  18  45]
  [ 94  18  45]
  [ 94  18  45]]

 [[ 89  16  41]
  [ 89  16  41]
  [ 89  16  41]
  ...
  [ 59  13  25]
  [ 59  13  25]
  [ 59  13  25]]]


array([3, 2, 2, ..., 1, 1, 1])

In [8]:
X = X.astype('float')

In [9]:
X /= 255.0 

In [10]:
X.shape

(7895, 150, 150, 3)

In [11]:
# construct the image generator for data augmentation
from keras.preprocessing.image import ImageDataGenerator
aug = ImageDataGenerator()

Using TensorFlow backend.


In [12]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
lb = LabelEncoder()
y = np_utils.to_categorical(lb.fit_transform(y))

In [13]:
import keras
#base = keras.applications.nasnet.NASNetLarge(input_shape=None, include_top=False, weights=None, input_tensor=None, pooling=None, classes=10)
base = keras.applications.inception_resnet_v2.InceptionResNetV2(include_top=False, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=10)

In [14]:
test_lst = np.array(test.slice_file_name.tolist())
folds = np.array(test.fold)
test_lst = [loc +'\\'+'fold'+str(fold)+'\\'+ s + '.jpg' for s,fold in zip(test_lst,folds)]
#print(test_lst)
test_X = []
for s in test_lst:
    test_X.append(cv2.resize(cv2.imread(s, cv2.IMREAD_COLOR),(150,150),interpolation=cv2.INTER_CUBIC))
#X = [cv2.imshow('img',s) for s in X]
test_X = np.array(test_X)
test_X = test_X.astype('float')
test_X /= 255.0 
test_y = np.array(test.classID.tolist())
test_y = np_utils.to_categorical(lb.fit_transform(test_y))
print(test_X.shape)

(837, 150, 150, 3)


In [15]:
from keras.preprocessing import image
from keras.models import Model
from keras.layers import Dense, GlobalAveragePooling2D
from keras import backend as K
from keras.optimizers import SGD

BS = 24
EPOCHS = 25
x = base.output
x = GlobalAveragePooling2D()(x)
x = Dense(1024, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)
model = Model(inputs=base.input, outputs=predictions)
for layer in base.layers:
    layer.trainable = True
model.compile(optimizer=SGD(lr=0.01, momentum=0.9), loss='categorical_crossentropy', metrics=['categorical_accuracy','top_k_categorical_accuracy'])
model.fit_generator(aug.flow(X, y, batch_size=BS),
	steps_per_epoch=7895 // BS,
	epochs=EPOCHS, verbose=1)

Epoch 1/25
328/328 [==============================] - 197s 600ms/step - loss: 0.7272 - categorical_accuracy: 0.7603 - top_k_categorical_accuracy: 0.9696
Epoch 2/25
328/328 [==============================] - 160s 488ms/step - loss: 0.2397 - categorical_accuracy: 0.9196 - top_k_categorical_accuracy: 0.9985
Epoch 3/25
328/328 [==============================] - 160s 487ms/step - loss: 0.1396 - categorical_accuracy: 0.9552 - top_k_categorical_accuracy: 0.9996
Epoch 4/25
328/328 [==============================] - 160s 488ms/step - loss: 0.0700 - categorical_accuracy: 0.9756 - top_k_categorical_accuracy: 0.9999
Epoch 5/25
328/328 [==============================] - 160s 487ms/step - loss: 0.0738 - categorical_accuracy: 0.9771 - top_k_categorical_accuracy: 0.9997
Epoch 6/25
328/328 [==============================] - 160s 488ms/step - loss: 0.0431 - categorical_accuracy: 0.9854 - top_k_categorical_accuracy: 1.0000
Epoch 7/25
328/328 [==============================] - 160s 488ms/step - loss: 0.03

In [16]:
model.save(r'D:\Projects\urban_sound\model\model.h5')
model.save_weights(r'D:\Projects\urban_sound\model\model_weights.h5')

In [17]:
model.evaluate(x=test_X, y=test_y, batch_size=None, verbose=1)

837/837 [==============================] - 16s 19ms/step


[0.9365472377187478, 0.8231780167264038, 0.978494623655914]

In [18]:
test = data.loc[data['fold'] == 9]
train = data.loc[data['fold'] != 9]

In [ ]:
loc = r'D:\Projects\urban_sound\UrbanSound8K\audio'
img_lst = np.array(train.slice_file_name.tolist())
folds = np.array(train.fold)
print(img_lst.shape)
img_lst = [loc +'\\'+'fold'+str(fold)+'\\'+ s + '.jpg' for s,fold in zip(img_lst,folds)]
X = []
for s in img_lst:
    X.append(cv2.resize(cv2.imread(s, cv2.IMREAD_COLOR),(150,150),interpolation=cv2.INTER_CUBIC))
#X = [cv2.imshow('img',s) for s in X]
X = np.array(X)
X = X.astype('float')
X /= 255.0 
y = np_utils.to_categorical(lb.fit_transform(y))
y = np.array(train.classID.tolist())

(7916,)


In [ ]:
test_lst = np.array(test.slice_file_name.tolist())
folds = np.array(test.fold)
test_lst = [loc +'\\'+'fold'+str(fold)+'\\'+ s + '.jpg' for s,fold in zip(test_lst,folds)]
#print(test_lst)
test_X = []
for s in test_lst:
    test_X.append(cv2.resize(cv2.imread(s, cv2.IMREAD_COLOR),(150,150),interpolation=cv2.INTER_CUBIC))
#X = [cv2.imshow('img',s) for s in X]
test_X = np.array(test_X)
test_X = test_X.astype('float')
test_X /= 255.0 
test_y = np.array(test.classID.tolist())
test_y = np_utils.to_categorical(lb.fit_transform(test_y))
print(test_X.shape)

In [ ]:
base = keras.applications.inception_resnet_v2.InceptionResNetV2(include_top=False, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=10)

BS = 24
EPOCHS = 25
x = base.output
x = GlobalAveragePooling2D()(x)
x = Dense(1024, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)
model = Model(inputs=base.input, outputs=predictions)

for layer in base.layers:
    layer.trainable = False
model.compile(optimizer=SGD(lr=0.01, momentum=0.9), loss='categorical_crossentropy', metrics=['categorical_accuracy','top_k_categorical_accuracy'])
model.fit_generator(aug.flow(X, y, batch_size=BS),
	steps_per_epoch=7895 // BS,
	epochs=EPOCHS, verbose=1)

In [ ]:
model.evaluate(x=test_X, y=test_y, batch_size=None, verbose=1)

In [ ]:
model.save()model.save(r'D:\Projects\urban_sound\model\model_2.h5')
model.save_weights(r'D:\Projects\urban_sound\model\model_weights_2.h5')

In [ ]:
test = data.loc[data['fold'] == 8]
train = data.loc[data['fold'] != 8]